import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <AntdRegistry>
                <ConfigProvider
                    theme={{
                        token: {
                            colorPrimary: "#9D9D9D",
                            colorText: "white", // 全局文字顏色設為白色
                            colorLinkHover: "gray",
                            colorTextDescription: "white",
                            colorBgContainer: "black",
                        },
                    }}
                >
                    <body className={inter.className}>{children}</body>
                </ConfigProvider>
            </AntdRegistry>
        </html>
    );
}
